---
- include: ../../erlapp.yml
  vars:
      name: soap_srv
      version: "{{soap_version}}"
      global_data_dir: false

- name: "Provision config"
  template: src=sys.config.j2
            dest=/opt/soap_srv-{{soap_version}}/releases/1/sys.config
