---
- include: ../../erlapp.yml
  vars:
      name: mm_srv
      version: "{{mm_version}}"
      global_data_dir: false

- name: "Provision config"
  template: src=sys.config.j2
            dest=/opt/mm_srv-{{mm_version}}/releases/1/sys.config
