---
- include: ../../erlapp.yml
  vars:
      name: smppsink
      version: "{{smppsink_version}}"
      global_data_dir: false
      global_log_dir: false

- name: "Provision config"
  template: src=sys.config.j2
            dest=/opt/smppsink-{{smppsink_version}}/releases/1/sys.config
